---
# file: roles/smokeping/tasks/main.yml

- name: install smokeping via apt
  apt: pkg={{ item }}
  with_items:
    - smokeping
    - sendmail
  tags: smokeping

- name: configure smokeping in /etc/smokeping/config.d
  template: src={{ item }} dest=/etc/smokeping/config.d/{{ item }} owner=root group=root mode=644
  with_items:
    - Alerts
    - General
    - Targets
  tags: smokeping
  notify:
    - restart smokeping

- name: link to smokeping config in /etc/apache2/conf-available
  shell: creates=/etc/apache2/conf-available/smokeping.conf chdir=/etc/apache2/conf-available ln -s ../../smokeping/apache2.conf smokeping.conf
  when: ansible_distribution_version not in ["12.04", "12.10", "13.04"]
  tags: smokeping

- name: enable the smokeping apache2 configuration
  shell: a2enconf smokeping
  when: ansible_distribution_version not in ["12.04", "12.10", "13.04"]
  tags: smokeping

- name: enable the cgid apache2 module
  shell: a2enmod cgid
  tags: smokeping
  notify:
    - reload apache config
